/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas4;
import java.awt.*;
import java.awt.event.*;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
/**
 *
 * @author ASUS
 */
public class rada2 extends javax.swing.JFrame {
    Integer berat,diskon;
    Float Total,hasil;
    /**
     * Creates new form rada2
     */
    public rada2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bexit = new javax.swing.JButton();
        badan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txnama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtelpon = new javax.swing.JTextField();
        txberat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bproses = new javax.swing.JButton();
        bulang = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasilisi = new javax.swing.JTextArea();
        Sdiskon = new javax.swing.JSlider();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rr = new javax.swing.JRadioButton();
        re = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel1MouseMoved(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("FORM ISIAN");

        bexit.setText("keluar");
        bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bexit))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(bexit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        badan.setBackground(new java.awt.Color(255, 51, 51));
        badan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                badanMouseDragged(evt);
            }
        });

        jLabel2.setText("Nama");

        txnama.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txnamaCaretUpdate(evt);
            }
        });
        txnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txnamaActionPerformed(evt);
            }
        });

        jLabel3.setText("No Telpon");

        txtelpon.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtelponCaretUpdate(evt);
            }
        });
        txtelpon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtelponActionPerformed(evt);
            }
        });
        txtelpon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtelponKeyPressed(evt);
            }
        });

        txberat.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txberatCaretUpdate(evt);
            }
        });
        txberat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txberatActionPerformed(evt);
            }
        });
        txberat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txberatKeyPressed(evt);
            }
        });

        jLabel4.setText("Berat barang");

        bproses.setText("PROSES");
        bproses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprosesActionPerformed(evt);
            }
        });

        bulang.setText("ULANG");
        bulang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bulangMouseClicked(evt);
            }
        });

        jLabel8.setText("kg");

        javax.swing.GroupLayout badanLayout = new javax.swing.GroupLayout(badan);
        badan.setLayout(badanLayout);
        badanLayout.setHorizontalGroup(
            badanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(badanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(badanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(badanLayout.createSequentialGroup()
                        .addGroup(badanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bproses)
                            .addGroup(badanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bulang))
                    .addGroup(badanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtelpon, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, badanLayout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(badanLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(txberat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        badanLayout.setVerticalGroup(
            badanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(badanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(badanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txberat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(badanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bproses)
                    .addComponent(bulang))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));

        hasilisi.setColumns(20);
        hasilisi.setRows(5);
        hasilisi.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                hasilisiMouseMoved(evt);
            }
        });
        hasilisi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hasilisiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(hasilisi);

        Sdiskon.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SdiskonStateChanged(evt);
            }
        });

        jLabel5.setText("%");

        jLabel6.setText("Total Harga");

        buttonGroup1.add(rr);
        rr.setText("Regular");

        buttonGroup1.add(re);
        re.setText("Express");

        jLabel7.setText("Paket");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(rr)
                        .addGap(32, 32, 32)
                        .addComponent(re)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(91, 91, 91))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Sdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Sdiskon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(re)
                    .addComponent(rr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(badan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(badan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bexitActionPerformed
     System.exit(0);
    }//GEN-LAST:event_bexitActionPerformed

    private void bprosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprosesActionPerformed
        // TODO add your handling code here:
        float Diskon, Reguler=11500, Total=0, Berat, TotalDiskon;
        String nama, nohp, paket;
        
        nama = txnama.getText();
        nohp = txtelpon.getText();
        Berat = Float.parseFloat(txberat.getText());
        
        Diskon = Float.valueOf(Sdiskon.getValue());
        
        
        
        if(rr.isSelected()){
            paket = rr.getText();
            TotalDiskon = Reguler * (Diskon/100) * Berat;
            Total = (Reguler * Berat) - TotalDiskon;
            
        }
        else if(re.isSelected()){
            paket = re.getText();
            TotalDiskon = (float) (Reguler * 1.5 * (Diskon/100) * Berat);
            Total = (float) ((Reguler * Berat* 1.5) - TotalDiskon);
        }
        else {
            JOptionPane.showMessageDialog(null, "Pilih Jenis Jasa Pengiriman Terlebih Dahulu","PERINGATAN", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        hasilisi.setText(
                "\n "
                        + " Nama\t: "+nama+
                        "\n No.HP\t: "+nohp+
                        "\n Berat\t: "+Berat+" Kg"+
                        "\n Diskon\t: "+TotalDiskon+
                        "\n Jenis Jasa\t: "+paket+
                        "\n Total\t: Rp "+Total+
                        "\n");
        
        
                                                
    }//GEN-LAST:event_bprosesActionPerformed

    private void txnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txnamaActionPerformed

    private void txberatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txberatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txberatActionPerformed

    private void txtelponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtelponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtelponActionPerformed

    private void bulangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bulangMouseClicked
        // TODO add your handling code here:
        txnama.setText("");
        txtelpon.setText("");
        txberat.setText("");
        hasilisi.setText("");
        buttonGroup1.clearSelection();
        Sdiskon.setValue(50);
    }//GEN-LAST:event_bulangMouseClicked

    private void txnamaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txnamaCaretUpdate
        // TODO add your handling code here:
         if (txnama.getText().length()== 0 || txberat.getText().equals("0")){
            bproses.setEnabled(false);
        }
        else if (txnama.getText().length()!=0 && txtelpon.getText().length()!=0 && txberat.getText().length()!=0){
            bproses.setEnabled(true);
        }
    }//GEN-LAST:event_txnamaCaretUpdate

    private void txtelponCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtelponCaretUpdate
        // TODO add your handling code here:
          if (txtelpon.getText().length()== 0 ||  txberat.getText().equals("0")){
            bproses.setEnabled(false);
        }
        else if (txnama.getText().length()!=0 && txtelpon.getText().length()!=0 && txberat.getText().length()!=0){
            bproses.setEnabled(true);
        }
    }//GEN-LAST:event_txtelponCaretUpdate

    private void txberatCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txberatCaretUpdate
        // TODO add your handling code here:
         if (txberat.getText().length()== 0 || txberat.getText().equals("0")){
            bproses.setEnabled(false);
        }
        else if (txnama.getText().length()!=0 && txtelpon.getText().length()!=0 && txberat.getText().length()!=0){
            bproses.setEnabled(true);
        }
    }//GEN-LAST:event_txberatCaretUpdate

    private void SdiskonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SdiskonStateChanged
        // TODO add your handling code here:
        jLabel5.setText(String.valueOf(Sdiskon.getValue()) + "%");
    }//GEN-LAST:event_SdiskonStateChanged

    private void txtelponKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtelponKeyPressed
       
         txtelpon.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
            char k = e.getKeyChar();
            if(!((k >= '0') && (k <= '9')) || (k == '\b')){
                e.consume();
            }
            }
            
}); 
    }//GEN-LAST:event_txtelponKeyPressed

    private void txberatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txberatKeyPressed
        // TODO add your handling code here:
         txberat.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
            char k1 = e.getKeyChar();
            if(((k1 < '0') || (k1 > '9')) && (k1 != '.')){
                e.consume();}}
            
});
    }//GEN-LAST:event_txberatKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txnama.setText("");
        txtelpon.setText("");
        txberat.setText("");
        hasilisi.setText("");
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       // JOptionPane.showMessageDialog(this, "Jika ingin keluar tolong tekan tombol keluar");
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Jika ingin keluar tolong tekan tombol keluar");
    }//GEN-LAST:event_formWindowClosing

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        // TODO add your handling code here:
        jPanel1.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPanel1MouseEntered

    private void badanMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_badanMouseDragged
        // TODO add your handling code here:
        badan.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_badanMouseDragged

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
        jPanel4.setBackground(Color.GREEN);       
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
        jPanel4.setBackground(Color.YELLOW); 
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseMoved
        // TODO add your handling code here:
        jPanel1.setBackground(Color.YELLOW); 
    }//GEN-LAST:event_jPanel1MouseMoved

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        // TODO add your handling code here:
        jPanel1.setBackground(Color.red); 
    }//GEN-LAST:event_jPanel1MouseExited

    private void hasilisiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hasilisiMouseClicked
        // TODO add your handling code here:
       // badan.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_hasilisiMouseClicked

    private void hasilisiMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hasilisiMouseMoved
        // TODO add your handling code here:
       // badan.setBackground(Color.MAGENTA);
    }//GEN-LAST:event_hasilisiMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rada2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rada2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rada2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rada2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rada2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider Sdiskon;
    private javax.swing.JPanel badan;
    private javax.swing.JButton bexit;
    private javax.swing.JButton bproses;
    private javax.swing.JButton bulang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea hasilisi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton re;
    private javax.swing.JRadioButton rr;
    private javax.swing.JTextField txberat;
    private javax.swing.JTextField txnama;
    private javax.swing.JTextField txtelpon;
    // End of variables declaration//GEN-END:variables
}
