/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postest3;

/**
 *
 * @author wildan
 */
public class tugas extends javax.swing.JFrame {

    /**
     * Creates new form tugas
     */
    public tugas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneljadwal = new javax.swing.JPanel();
        satpamsenin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        satpamrabu = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        satpamselasa = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        satpamkamis = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        satpamjumat = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        satpamsabtu = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        satpamminggu = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        senin = new javax.swing.JButton();
        selasa = new javax.swing.JButton();
        rabu = new javax.swing.JButton();
        kamis = new javax.swing.JButton();
        jumat = new javax.swing.JButton();
        sabtu = new javax.swing.JButton();
        minggu = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPaneljadwal.setBackground(new java.awt.Color(153, 153, 153));
        jPaneljadwal.setLayout(new java.awt.CardLayout());

        satpamsenin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("1. Budi");
        satpamsenin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 95, -1, -1));

        jLabel3.setText("2. Rudi");
        satpamsenin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 127, -1, -1));

        jLabel4.setText("3. Sardi");
        satpamsenin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 159, -1, -1));

        jLabel5.setText("4. Sukidi");
        satpamsenin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 191, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel6.setText("Satpam senin");
        satpamsenin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 9, 280, -1));

        jPaneljadwal.add(satpamsenin, "card2");

        satpamrabu.setBackground(new java.awt.Color(204, 204, 204));
        satpamrabu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel12.setText("Satpam rabu");
        satpamrabu.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 9, 280, -1));

        jLabel13.setText("1. Budak");
        satpamrabu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 95, -1, -1));

        jLabel14.setText("2. Randi");
        satpamrabu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 127, -1, -1));

        jLabel15.setText("3. Sneider");
        satpamrabu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 159, -1, -1));

        jLabel16.setText("4. tsubasa");
        satpamrabu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 191, -1, -1));

        jPaneljadwal.add(satpamrabu, "card3");

        satpamselasa.setBackground(new java.awt.Color(204, 204, 204));
        satpamselasa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel7.setText("Satpam selasa");
        satpamselasa.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 9, 260, -1));

        jLabel8.setText("1.Naufal");
        satpamselasa.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 95, -1, -1));

        jLabel9.setText("2. Ridho");
        satpamselasa.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 127, -1, -1));

        jLabel10.setText("3. Lucky");
        satpamselasa.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 159, -1, -1));

        jLabel11.setText("4. Irfan");
        satpamselasa.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 191, -1, -1));

        jPaneljadwal.add(satpamselasa, "card4");

        satpamkamis.setBackground(new java.awt.Color(204, 204, 204));
        satpamkamis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel17.setText("Satpam kamis");
        satpamkamis.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 9, 280, -1));

        jLabel18.setText("1. agung");
        satpamkamis.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 95, -1, -1));

        jLabel19.setText("2. wasito");
        satpamkamis.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 127, -1, -1));

        jLabel20.setText("3. arif");
        satpamkamis.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 159, -1, -1));

        jLabel21.setText("4. rahman");
        satpamkamis.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 191, -1, -1));

        jPaneljadwal.add(satpamkamis, "card5");

        satpamjumat.setBackground(new java.awt.Color(204, 204, 204));
        satpamjumat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel22.setText("Satpam Jumat");
        satpamjumat.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 9, 280, -1));

        jLabel23.setText("1. Andi");
        satpamjumat.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 95, -1, -1));

        jLabel24.setText("2. Rivaldy");
        satpamjumat.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 127, -1, -1));

        jLabel25.setText("3. Eko");
        satpamjumat.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 159, -1, -1));

        jLabel26.setText("4. liani");
        satpamjumat.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 191, -1, -1));

        jPaneljadwal.add(satpamjumat, "card6");

        satpamsabtu.setBackground(new java.awt.Color(204, 204, 204));
        satpamsabtu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel27.setText("Satpam sabtu");
        satpamsabtu.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 9, 280, -1));

        jLabel28.setText("1. dani");
        satpamsabtu.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 95, -1, -1));

        jLabel29.setText("2. Rivaldy");
        satpamsabtu.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 127, -1, -1));

        jLabel30.setText("3. Eko");
        satpamsabtu.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 159, -1, -1));

        jLabel31.setText("4. liani");
        satpamsabtu.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 191, -1, -1));

        jPaneljadwal.add(satpamsabtu, "card7");

        satpamminggu.setBackground(new java.awt.Color(204, 204, 204));
        satpamminggu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI Light", 0, 36)); // NOI18N
        jLabel32.setText("Satpam minggu");
        satpamminggu.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 9, 280, -1));

        jLabel33.setText("1. dani");
        satpamminggu.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 95, -1, -1));

        jLabel34.setText("2. Rivaldy");
        satpamminggu.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 127, -1, -1));

        jLabel35.setText("3. Eko");
        satpamminggu.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 159, -1, -1));

        jLabel36.setText("4. liani");
        satpamminggu.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 191, -1, -1));

        jPaneljadwal.add(satpamminggu, "card8");

        getContentPane().add(jPaneljadwal, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 0));
        jLabel1.setText("Sistem Informasi Ronda Jaga Malam tanpa Dirimu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 50));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        senin.setText("senin");
        senin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seninActionPerformed(evt);
            }
        });
        jPanel3.add(senin);

        selasa.setText("selasa");
        selasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selasaActionPerformed(evt);
            }
        });
        jPanel3.add(selasa);

        rabu.setText("rabu");
        rabu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rabuActionPerformed(evt);
            }
        });
        jPanel3.add(rabu);

        kamis.setText("kamis");
        kamis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kamisActionPerformed(evt);
            }
        });
        jPanel3.add(kamis);

        jumat.setText("jumat");
        jumat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumatActionPerformed(evt);
            }
        });
        jPanel3.add(jumat);

        sabtu.setText("sabtu");
        sabtu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sabtuActionPerformed(evt);
            }
        });
        jPanel3.add(sabtu);

        minggu.setText("minggu");
        minggu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mingguActionPerformed(evt);
            }
        });
        jPanel3.add(minggu);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Absensi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(43, 43, 43))
        );

        getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 273, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seninActionPerformed
satpamsenin.setVisible(true);
satpamselasa.setVisible(false);
satpamrabu.setVisible(false);
satpamkamis.setVisible(false);
satpamjumat.setVisible(false);
satpamsabtu.setVisible(false);
satpamminggu.setVisible(false);

// TODO add your handling code here:
    }//GEN-LAST:event_seninActionPerformed

    private void selasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selasaActionPerformed
satpamsenin.setVisible(false);
satpamselasa.setVisible(true);
satpamrabu.setVisible(false);
satpamkamis.setVisible(false);
satpamjumat.setVisible(false);
satpamsabtu.setVisible(false);
satpamminggu.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_selasaActionPerformed

    private void rabuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rabuActionPerformed
satpamsenin.setVisible(false);
satpamselasa.setVisible(false);
satpamrabu.setVisible(true);
satpamkamis.setVisible(false);
satpamjumat.setVisible(false);
satpamsabtu.setVisible(false);
satpamminggu.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_rabuActionPerformed

    private void kamisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kamisActionPerformed
satpamsenin.setVisible(false);
satpamselasa.setVisible(false);
satpamrabu.setVisible(false);
satpamkamis.setVisible(true);
satpamjumat.setVisible(false);
satpamsabtu.setVisible(false);
satpamminggu.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_kamisActionPerformed

    private void jumatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumatActionPerformed
satpamsenin.setVisible(false);
satpamselasa.setVisible(false);
satpamrabu.setVisible(false);
satpamkamis.setVisible(false);
satpamjumat.setVisible(true);
satpamsabtu.setVisible(false);
satpamminggu.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_jumatActionPerformed

    private void sabtuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sabtuActionPerformed
satpamsenin.setVisible(false);
satpamselasa.setVisible(false);
satpamrabu.setVisible(false);
satpamkamis.setVisible(false);
satpamjumat.setVisible(false);
satpamsabtu.setVisible(true);
satpamminggu.setVisible(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_sabtuActionPerformed

    private void mingguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mingguActionPerformed
satpamsenin.setVisible(false);
satpamselasa.setVisible(false);
satpamrabu.setVisible(false);
satpamkamis.setVisible(false);
satpamjumat.setVisible(false);
satpamsabtu.setVisible(false);
satpamminggu.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_mingguActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
jempol tampil = new jempol();
//tugas tugu = new tugas();
        tampil.setVisible(true);
       // tugu.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPaneljadwal;
    private javax.swing.JButton jumat;
    private javax.swing.JButton kamis;
    private javax.swing.JButton minggu;
    private javax.swing.JButton rabu;
    private javax.swing.JButton sabtu;
    private javax.swing.JPanel satpamjumat;
    private javax.swing.JPanel satpamkamis;
    private javax.swing.JPanel satpamminggu;
    private javax.swing.JPanel satpamrabu;
    private javax.swing.JPanel satpamsabtu;
    private javax.swing.JPanel satpamselasa;
    private javax.swing.JPanel satpamsenin;
    private javax.swing.JButton selasa;
    private javax.swing.JButton senin;
    // End of variables declaration//GEN-END:variables
}
